### ISSUE TITLE
Make docs neutral and clean from "ads"

### ISSUE THREAD

**Issue by igorsantos07** [i18next/react-i18next-gitbook#114]
## 🚀 Feature Proposal

I'm getting started with i18next and I found it a bit........ confusing....... that there's a couple of semi-related "ads" on the introduction page. Why there's a mention of the translation-check plugin right at the start? And then, the page ends with a long, camouflaged ad on Locize.

Not to mention the ad links at the header of the docs as well, intermixed with a link to the main i18next docs...

It's also _interesting_ how there's a bunch of "check docs for this _here_" but when it comes to Locize, you do use SEO-friendly links, which might even seem sneaky at some spots.

**Edit:** I noticed later that the exact same suggestions happen at the [i18next Extractor](https://www.i18next.com/how-to/extracting-translations) docs (also tangential, since for instance translation-check is not an extraction tool but an inspector). This repetition of specific tool suggestions makes it a bit smelly, even for an inattentive reader. It also shows in a lot of other spots (such as Intro, History, Comparison...). I'm mentioning it here so I don't repeat the issue across repos without further discussion, since I'm sure this is a sensitive topic.

## Motivation

I understand this is how you monetize the development, but the way many parts of the docs are written feels _weird_, to put it kindly. That site is for docs on how to use it, we are not supposed to try to interpret if "this is useful for what I want" or "this is an ad for a related service". There are a couple of passages that might feel biased in the i18next docs too.

Besides that, why's a specific plugin (home-made, btw) suggested on the home page instead of any other plugin, for instance? Not to mention other services also link with i18next, but of course, Locize is the only one extensively mentioned (which kinda "makes sense", just doesn't seem fair, nor related).

## Example

I would suggest making the docs actually neutral and focused, by removing plugin or service suggestions from unrelated pages - leave these to pages on plugins and pluggable services... 

I hope this doesn't feel aggressive, but I really felt odd to see "internal ads" on multiple documentation pages while I'm trying to understand i18next's feature set, capabilities, and how it works. Not to mention they don't look like ads, since they're completely mixed with the actual content.

**Comment by jamuhl** [comment]
Can understand this request - but you might also understand that we do no other advertising for locize.

We did i18next 10 years and asked for nothing. Nowadays i18next is one of most used i18n lib in javascript / even most downloads for react i18n nowadays.

A lot of large companies use it but getting sponsorship out of those is close to impossible - so if you need financial support you're basically doomed in OSS -> either the project is crazy popular or you will burn out doing it for free (and believe me - there are not only nice people using your work).

I can understand advertising our own product can look unfair or unrelated -> but without it chances would be we would have to close i18next down

**Comment by igorsantos07** [comment]
Yeah, that same OSS sad story. I can relate.

But what about advertising the plugin in unrelated places? Does it earn the team some money as well, or just more public?

**Comment by igorsantos07** [comment]
I mean........... Even [code samples](https://react.i18next.com/getting-started#basic-sample) have Locize ads. For a newcomer to the i18n field, it may seem like the only way to do it is using Locize and this foreign territory is dominated by JSON files and Locize. This paints a completely wrong picture, which goes beyond fairness or relatedness...

**Comment by adrai** [comment]
Where do you see code samples with locize usage in that page?

**Comment by jamuhl** [comment]
fair...really got to calm down a little if the topic is about being fair to rivals -> have a look at i18nexus.com -> do you feel it fair that built on top of i18next (even promoting itself with i18next) and neither being a member nor contributing to i18next (not sponsoring, nothing)...so please stop about talking fair. Or do you think it's fair to compete with companies having huge ad budgets

Yes the advertising for our locize is getting into your face -> but honestly I nowadays prefer 1 user going and trying locize because of the visual force than an other 100 users using in and not even think about the hard work and considering buying us a coffee.

**Comment by igorsantos07** [comment]
I was really talking about being fair with the developers who are reading the docs. Open source is terrible at those moments and I can't argue with you (never tried, actually, and if it seemed so, sorry!)

That said, you can still advertise the project in many different places and methods, but again, it's about fairness with the developer reading the docs: ads shouldn't be confusing, nor steer you away from your current objectives. Many sections in the docs are actually just ads, and could be boxed and noted as such (otherwise, the reader follows along with the topic and then stops to realize it's not "the next step"). Worse than that, some other parts also feel like documentation but are actually pointing to an unrelated service (to the topic being discussed in the page, like suggesting an inspector tool among extractors, instead of being a separate section in the plugins page).

This is my last cent on discussing the way the docs are read by newcomers. I guess, if you disagree, your point will be that you want to also be unfair using camouflaged ads and repetition, as to tip the scale back to your side and out of i18nexus - while I think there could be a middle-ground, I also understand :)

**Comment by igorsantos07** [comment]
Btw, I was looking into how Locize actually works (since I got moved away by the ad policy) and found a couple of small mistakes :)
We're currently using a free service, but will probably move into a paid tier in the future - which is very expensive, so I'm maintaining a list of backup services. I'll add Locize to it!

![image](https://user-images.githubusercontent.com/532299/128427844-2c67a4e1-2b3c-49cc-825f-6902b8d97610.png)

**Comment by adrai** [comment]
> Btw, I was looking into how Locize actually works (since I got moved away by the ad policy) and found a couple of small mistakes :)
> We're currently using a free service, but will probably move into a paid tier in the future - which is very expensive, so I'm maintaining a list of backup services. I'll add Locize to it!
> 
> ![image](https://user-images.githubusercontent.com/532299/128427844-2c67a4e1-2b3c-49cc-825f-6902b8d97610.png)

thank you for your help, just fixed those typos...
