### ISSUE TITLE
Getting started with escapeValue to false

### ISSUE THREAD

**Issue by SimonChaumet** [i18next/react-i18next-gitbook#116]
## Documentation issue

In the getting started guide in the [basic sample](https://react.i18next.com/getting-started#basic-sample), the options have an `escapeValue` to false.

## Motivation

This part doesn't seem important for this sample (as there is no interpolation) and this can leads into security issues for beginning users which don't understand this parameter. If there is a reason I think a comment explaining why would be great or remove this part if not necessary.

(Ready to open a PR if you think it should be removed)

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/128355712-e353da66-4da8-4c2f-9f87-bc741a514368.png)
