### ISSUE TITLE
Add examples of nesting, formatters with Trans

### ISSUE THREAD

**Issue by amandapouget** [i18next/react-i18next-gitbook#133]
## Documentation issue

The Trans documentation is great!~  I'm hoping it can be improved by adding an example of nesting. And, an example of formatting.

Formatter? Not sure if this is right and cannot find any examples on Google:
```
<Trans>Today's date is {{ date, SOME_DATE_FORMATTER }}</Trans>
```

Nesting:
```
No idea how to do this, but to display "13 of 52" for example:
const count = 13;
const total = 52;
...
<Trans count={13}>{{count, INTEGER}} <strong>of</strong>{t('{{count, INTEGER}}', { count: total })}</Trans>
```
or something like that.

## Motivation

Trans can be unintuitive to work with and adding these two examples (or whatever their working equivalents are) would greatly enhance the documentation. All the other nesting and formatter docs use the t function so the hole in the Trans documentation is quite daunting.

**Comment by jamuhl** [comment]
The trick in doing `<Trans>some {{ interpolateME }}</Trans>` is that `{{ interpolateME }}` gets handled as an object in Trans component children - which by nature would be invalid as objects are no react elements - but we take that and convert it to some interpolation value.

So, for nesting and interpolation with format this does not work and therefore it must be used like https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0 for such cases
