### ISSUE TITLE
Trans component docs incorrectly say it is does not rerender on language change.

### ISSUE THREAD

**Issue by loganripplinger** [i18next/react-i18next-gitbook#134]
## Documentation issue

> It does ONLY interpolation. It does not rerender on language change or load any translations needed. Check useTranslation hook or withTranslation HOC for those cases.

from https://github.com/i18next/react-i18next-gitbook/blob/8d4776e007b903c184beedeffd8e51a31f940e48/latest/trans-component.md?plain=1#L12

This does not seem to be true at all. I am able to use `<Trans>` and have it rerender correctly when my selected language changes.

## Motivation

Docs for Trans component seem to be wrong.

**Comment by jamuhl** [comment]
without having useTranslation somewhere up the tree?
