### ISSUE TITLE
Link to github gitbook repository

### ISSUE THREAD

**Issue by boly38** [i18next/react-i18next-gitbook#136]
## Documentation issue

As i18next user and related gitbook reader, I would like to know where the documentation source code is.

## Motivation

As i18next gitbook reader, when I encounter some broken links (ex [here](https://react.i18next.com/legacy-v9/trans-component))I want to fix them.

I took many time to find related git repository.

It would be great to have a link to **this** repository.

It seems that gitbook badge is only ads to gitbook service and not to this repository.

**Comment by adrai** [comment]
Yes, the old gitbook provided some sort of "edit on github" link...
Now the links are here: https://github.com/i18next/react-i18next#documentation
