### ISSUE TITLE
Selection on docs website is broken

### ISSUE THREAD

**Issue by Seasle** [i18next/react-i18next-gitbook#149]
## 🐛 Bug Report

On the website with documentation the mouse selection does not work, or rather it is not visible. I would like it to work correctly.

## To Reproduce

Just open the [website](https://react.i18next.com) (except for the Introduction page) and try to highlight something. Had a quick look at the cause, and the `--scalar-selection-background` and `--scalar-selection-color` variables are missing on `::selection`.

**Comment by adrai** [comment]
We use gitbook... seems that is the case for all websites on gitbook... (like: https://developers.deepl.com/docs) so you might want to add a issue here: https://github.com/GitbookIO/gitbook

**Comment by adrai** [comment]
will close, since there's not much we can do here
