### ISSUE TITLE
Testing with typescript

### ISSUE THREAD

**Issue by nicgirault** [i18next/react-i18next-gitbook#32]
In the testing doc (https://react.i18next.com/misc/testing) it says to export the component that is not wrapped with `withNamespaces`. However, when using typescript the base component must be provided all the props coming from `withNamespaces`. This is quite heavy to provide. Do you have any suggestion to deal with Typescript in tests?

**Comment by jamuhl** [comment]
@schettino could you please provide some insights here...

**Comment by Eugene-Sviridov** [comment]
@jamuhl I think @nicgirault talked about this case:

Class that will be used for test exported like this:
```
export class SomeComponent extends React.Component<Props & WithNamespaces> {
```
Then if we want to test ```SomeComponent``` we need to put i18n to ```props``` for the component because of ```WithNamespaces```.

Is there any way how we can avoid it? Ideally I want to pass only ```Props``` but I will not work because of ```t``` function

**Comment by jamuhl** [comment]
@Eugene-Sviridov with insights from @schettino i meant more an answer to the typescript specific problem - as i don't use typescript i have no idea of all those problems
