### ISSUE TITLE
Document want the Tag numbers (<1>) in translation files mean

### ISSUE THREAD

**Issue by NikeyMice** [i18next/react-i18next-gitbook#54]
By following this example https://react.i18next.com/latest/trans-component, it is unclear what the tag numbers mean in the translation file. Eventually was able to find this https://github.com/i18next/react-i18next/issues/342 but it would have been helpful to have this on the doc site. 

In the time that I have been working with this library, this area was the only thing I found that lacked in documentation.

**Comment by jamuhl** [comment]
For others coming to this issue - documentation can be found in the Trans Component section: https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
