### ISSUE TITLE
Documentation is difficult to read

### ISSUE THREAD

**Issue by vfonic** [i18next/react-i18next-gitbook#57]
Hi! Thanks for the great package!

I'm trying to understand how to correctly use and fully configure this package.

I see configuration options scattered here and there. The text throughout the documentation is mostly trying to sell me the use of the package. That's fine. Ok, let's say I'm on board. What next?

https://react.i18next.com/getting-started

### Install using npm

`$ npm install react-i18next --save`
These are different installation instructions than on the other page.
It would also be good to have "Install using yarn" section.

yarn is only randomly mentioned here:
https://github.com/i18next/react-i18next-gitbook/blob/db2ad5eb49604063514b7c6a5c0981d6814cc274/misc/using-with-icu-format.md

Here's different install instructions page:
https://react.i18next.com/guides/quick-start

Install both react-i18next and i18next package:
`npm install react-i18next i18next --save`
(notice also no `$` sign before, it's a small issue, but ideally, it would look the same)

What's the difference between "Getting started" and "Quick start" page? What's the purpose of having two pages?

"Quick start" page is the closest to what I was looking for when I came in search for i18n package to use in my react app.

Let's see some more examples:

### Load from CDN

There's no actual `<script>` tag in here. Just a direct link to javascript file. (Too bad unpkg doesn't have search feature like https://cdnjs.com/)

### Drawbacks of other i18n solutions

https://react.i18next.com/guides/the-drawbacks-of-other-i18n-solutions

> Let's make the sample using our own base i18n framework i18next. Like all other solutions, some come drawbacks.

> Before we come to the drawbacks let's highlight some advantage of those solutions above - they are very simple to get started.

> With loading translations asynchronous there comes another problem - does your framework handle the pending state during loading translation?

> In most frameworks you will end having to split this into multiple translation strings. But for your translators it would make sense to have this as one sentence to translate like eg.:

> In the `/dist` folder you find specific builds for `commonjs`, `es6 modules`,...

There are links in the README.md that are broken: https://github.com/i18next/react-i18next#v9

It's off-putting to have a package specified in language and grammar, have grammatical/spelling errors. Especially if you're offering translation services (which I'll most probably use! Thanks!). ...but please fix these.

Is there a single page where I can see all the configuration options for i18n package? Same for react-i18n package?

I understand there has been a lot of work put into this project. And I appreciate it. My feedback above is in hope to make it even better and to remove these little nuances to make this project truly shine. Because that's what these are, just little nuances that hide the full quality of the project. Thanks!

EDIT: I found the configuration options: 💪 https://www.i18next.com/overview/configuration-options 

EDIT 2: What's this `wait: true` option (https://github.com/i18next/react-i18next/issues/219)? Where can I read more about it?

**Comment by jamuhl** [comment]
wait: true is used in v9 -> v10 uses Suspense to handle pending loading states

**Comment by jamuhl** [comment]
Links in the README.md should be fixed now

Fully agree - grammar and spelling always is a problem - not sure if not being a native English speaker is a good excuse. The translation management service we offer does not include work of translators employed by us -> so there are no resources we could set on this without having to contract this out - and while locize is growing we're still a small company with a very tight budget.

Hopefully one day we could have a technical writer (more talented than me) to help out with documentation - but currently we try to improve step by step with the help of the community. (Still i18next exists for over 8 years now - free work - locize exists now for 2 years...and on the way to get sustainable (no external investors, no funding))

**Comment by vfonic** [comment]
That's amazing! :)

I understand and I'd probably end up in much worse position than how far you've gone with this project. I just wanted to share my feedback on how I got lost in the docs on this one. :)

Thanks for addressing these issues so quickly!

Keep up with the good work! 💪
(feel free to close this issue)
