### ISSUE TITLE
Suggestion fix for local translation files

### ISSUE THREAD

**Issue by drd-2rcl** [i18next/react-i18next-gitbook#61]
Is recommended in documentation add files in `(/public/locales/en/translation.json)`. But this is broken the application because this is not supported imports outside `src`

```Module not found: You attempted to import ../public/locales/en/translation.json which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.```

I recommend the change simple in docs: 
`public` => `src`
`(/src/locales/en/translation.json)`

`https://react.i18next.com/legacy-v9/step-by-step-guide`

**Comment by jamuhl** [comment]
that recommendation is when using xhr-backend (as public gets served by devserver) if you like to import those and add those on init add them under source)

but...bundling might not the best idea - hopefully you find out why (hint ... bundlesize)
