### ISSUE TITLE
React Hook "useTranslation" is called in function

### ISSUE THREAD

**Issue by mobeloper** [i18next/react-i18next-gitbook#65]
I am trying to use i18next inside a form model to store a mobx-state-tree 

My model form code has this structure...

---
import { types, flow, getRoot } from 'mobx-state-tree'

import {useTranslation} from 'react-i18next';

export const MyFormModel = types
.model('Form',{..})
.views(...)
.actions(self => ({
validate(){
//trying to use it here but makes the problem...
const {t} = useTranslation();
const msg = t('WRONG_NAME');
self.errors.set('userName', msg)
.
.
.
}))
type MyFormModelType = typeof MyFormModel.Type
export interface MyForm extends MyFormModelType {}

-------

I am confident my i18next configuration is correct because I am using i18next successfully in the rest of my app when using it in class or functional react components but, for this kind of form stores for mobx I am getting this error:
"React Hook "useTranslation" is called in function "validate" which is neither a React function component or a custom React Hook function  react-hooks/rules-of-hooks"

I just can't find the way to solve this. Any ideas or suggestions you can give me to solve this?

**Comment by jamuhl** [comment]
outside of react use it like you would use i18next import your i18n.js and use i18n.t

**Comment by mobeloper** [comment]
I am sorry, my app is a react app but I never use it outside react. Do you mind, giving me to an example or pointing me to reference?

**Comment by jamuhl** [comment]
```js
import i18n from 'i18next';

i18n.t(myKey);
```

**Comment by mobeloper** [comment]
You are awesome!! Thank you so much 😉

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
