### ISSUE TITLE
Actual Language

### ISSUE THREAD

**Issue by DanPHP7** [i18next/react-i18next-gitbook#71]
How can I get the actual language with hooks ?

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/usetranslation-hook#what-it-does

`const { t, i18n } = useTranslation();`

`i18n` is the instance and you can get: i18n.language, i18n.languages: https://www.i18next.com/overview/api#language

**Comment by DanPHP7** [comment]
Thank you!!
