### ISSUE TITLE
useTranslation hook with Typescript issue

### ISSUE THREAD

**Issue by paulconlin** [i18next/react-i18next-gitbook#72]
I'm currently using i18next v19.1.0 and react-i18next 11.3.1 with Typescript v3.7.2

When passing in a string key to the t function from useTranslation(), it keeps saying - 
```
Expected 0 arguments, but got 1.
```

![image](https://user-images.githubusercontent.com/10995964/74480898-61605780-4e77-11ea-997b-e7e865778651.png)

I feel like I might just be missing something basic. Any ideas?

**Comment by paulconlin** [comment]
Found the issue, apologies

**Comment by LoLei** [comment]
I'm currently facing the same issue (only in Docker though, for some reason.)

Could you share your solution, please? 🙂

**Comment by riccardolardi** [comment]
Same issue, @LoLei found any solution yet?

**Comment by riccardolardi** [comment]
Just figured out downgrading `i18next` to `23.6.0` will get rid of the issue.

**Comment by LoLei** [comment]
@riccardolardi 

I think I solved my case as well, first, to fix it in general, apply this solution: https://github.com/i18next/react-i18next/issues/1601#issuecomment-1426633981

The reason why it happens only in Docker, seems to be the version of `yarn`, at least for me.

Docker images of `node` ship with `yarn` version 1 by default.

Running `yarn set version stable` (version 3 or 4 is fine) and then re-installing the dependencies with `yarn install` and rebuilding the project fixes it in Docker for me as well.

**Comment by 1020850886** [comment]
When I upgraded from 23.4.0 to 23.4.1, this error occurred in all places where the t function was used. How can I fix it? @LoLei @riccardolardi @paulconlin

**Comment by vizzyo** [comment]
i got the same error:
![image](https://github.com/user-attachments/assets/2d828fa5-d386-43f8-9565-4f549e0a69cb)


```
  "i18n": "^0.15.1",
    "i18next": "^24.0.5",
    "jshashes": "^1.0.8",
    "lodash.get": "^4.4.2",
    "miniprogram-ci": "2.0.9",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-i18next": "^15.1.3",
    ```

**Comment by xpioneer** [comment]
I got the same error:
`
ERROR in ./src/pages/login/index.tsx:39:19
TS2554: Expected 0 arguments, but got 1.
    37 |   useEffect(() => {
    38 |     const typed = new Typed(el.current, {
  > 39 |       strings: [t('introduction')],
       |                   ^^^^^^^^^^^^^^
    40 |       startDelay: 200,
    41 |       typeSpeed: 50,
    42 |       loop: true,

// package.json

"i18next": "^24.1.2",
"react-i18next": "^15.2.0",
"typescript": "^4.9.5",

Has anyone else encountered it

**Comment by woowalker** [comment]
> I encountered the following TypeScript error during compilation:
> 
> ERROR in ./src/pages/login/index.tsx:39:19 TS2554: Expected 0 arguments, but got 1. 37 | useEffect(() => { 38 | const typed = new Typed(el.current, {
> 
> > 39 |       strings: [t('introduction')],
> > |                   ^^^^^^^^^^^^^^
> > 40 |       startDelay: 200,
> > 41 |       typeSpeed: 50,
> > 42 |       loop: true,
> 
> Here's my `package.json`:
> 
> "i18next": "^24.1.2", "react-i18next": "^15.2.0", "typescript": "^4.9.5",
> 
> I upgraded TypeScript to:
> 
> "typescript": "^5.7.2",
> 
> After the upgrade, the error was resolved.
> 
> ### Analysis:
> 1. The error occurs because TypeScript 4.9.x's type inference for `react-i18next`'s `useTranslation` and its `t` function does not align perfectly with `i18next` v24.1.2.
> 2. Upgrading TypeScript to 5.7.2 resolves the issue, likely due to improved type inference or updates in handling `react-i18next`'s type definitions.
> 
> ### Solution:
> If you encounter this issue, upgrading TypeScript to 5.x or later should resolve it. Alternatively, you could suppress the error by explicitly typing `t` or updating your type definitions, though upgrading is the most straightforward solution.

save my life
