### ISSUE TITLE
Need help with markdown 

### ISSUE THREAD

**Issue by ozbillwang** [i18next/react-i18next-gitbook#78]
In https://react.i18next.com/legacy-v9/interpolate#alternatives, it mentions the usage about `markdown`

>b) use markdown, eg. react-remarkable and pass markdown formatted content from translations to the markdown component.

But no sample on how to use them together. 

Could you show me some codes about this topic?

**Comment by jamuhl** [comment]
the markdown component expects a STRING - t(key) gives you a string

where is the difficulty?

**Comment by ozbillwang** [comment]
so what the real code looks like? If I need add a markdown string.

    **Markdown is awesome!**

or

    ## Reasons React is great

**Comment by jamuhl** [comment]
depends on markdown implementation...not i18next
