### ISSUE TITLE
document <Trans /> `link` reserved tag name

### ISSUE THREAD

**Issue by froger** [i18next/react-i18next-gitbook#87]
## 🐛 Bug Report

As documented in [Alternative Usage](https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0), I've tried to used named tag for `<Trans />` with the tag key `link`.

It doesn't work as expected, as it seems there are some reserved names for using <Trans /> react-i18next component. 
I would expect the documentation to warn about this restriction. 

## To Reproduce

```js
<Trans
  i18nKey="goToMeeting"
  components={{
    link: <Link to={`/${orgId}/meetings`} />,
  }}
 />
```

```json
{
  "goToMeeting": "Open <link>meetings</link>
}
```
```html
<!-- result -->
Open <link />meetings
```

But if I use another tag name, like `a`, it does work : 

```js
<Trans
  i18nKey="goToMeeting"
  components={{
     a: <Link to={`/${orgId}/meetings`} />,
   }}
 />
```
```json
{
  "goToMeeting": "Open <a>meetings</a>
}
```
```html
<!-- result -->
Open <a href="/1/meetings">meetings</a>
```

## Expected behavior

```js
<Trans
  i18nKey="goToMeeting"
  components={{
     link: <Link to={`/${orgId}/meetings`} />,
   }}
 />
```
```json
{
  "goToMeeting": "Open <link>meetings</link>
}
```
```html
<!-- result -->
Open <a href="/1/meetings">meetings</a>
````

## Your Environment

- *runtime version*: Chrome 85
- *i18next version*: 19.6.3
- *react-i18next*: 11.7.0
- *os*: Mac

--- 

Thanks for this awesome component!

**Comment by jamuhl** [comment]
The choosen tag name can not be an element that exists in HTML and is self-closing:

try uppercase Link like (both in code and translation):

```js
<Trans
  i18nKey="goToMeeting"
  components={{
    Link: <Link to={`/${orgId}/meetings`} />,
  }}
 />
```

**Comment by froger** [comment]
Thanks, @jamuhl, that is working. 
Still, I would expect the documentation to state this restriction as it was quite a frustrating experience (`link` and `img` is key names I would have tried to use naturally). 
I've made a PR to warn about key names and I am closing this issue.

**Comment by jamuhl** [comment]
If I got time I will check if we can improve this - so link and other reserved tags will work at some point...
