### ISSUE TITLE
Deep keys does not work

### ISSUE THREAD

**Issue by Kachyz** [i18next/react-i18next-gitbook#98]
## 🐛 Bug Report

Trying to use deep keys does not work as expected. This is my `ns`
```json
alerts: {
  type: {
     t1: "low",
     t2: "high"
  },
  msg: "alert message"
}
```

Using `useTranslate('alerts');` I can print next block with no problem
```js
t('msg')
```

But I can not print `t1`. I have tried next lines
```js
t('type.t1');
t('type:t1');
t('alerts:type.t1');
t('alerts:type:t1');
```
And the only string that I receive is the same key I'm sending.

I have tried `returnObjects: true` option and it does return whole object but as far as I can tell we should be able to extract just an inner key of that object

## To Reproduce

Here is a codeSandbox to check if `t1` in `test` is displayed
A [codesandbox](https://codesandbox.io/s/internationalization-dynamic-forked-ntucs?file=/src/app.js) 

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: yarn 1.19.1
- *i18next version*: react-i18next@11.7.3
- *os*: Mac
- *react*: react@16.13.1

**Comment by adrai** [comment]
You probably set the keySeparator option to false...
remove that option or set keySeparator to '.'

**Comment by Kachyz** [comment]
@adrai you are right, that was the problem. 
Thank you !!!
